name: CI reusable
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
    - main
  pull_request:
  workflow_run:
    workflows: [ "update_docker" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  to-lowercase:
    runs-on: ubuntu-latest
    outputs:
      repo_lowercase: ${{ steps.lowercase.outputs.repository }}
    steps:
      - id: lowercase
        run: |
          echo "repository=ghcr.io/${GITHUB_REPOSITORY,,}:jazzy" >> $GITHUB_OUTPUT
  test:
    needs: to-lowercase
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.to-lowercase.outputs.repo_lowercase }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: suturo_resources
      - uses: actions/checkout@v4
        with:
          path: cognitive_robot_abstract_machine
          repository: SUTURO/cognitive_robot_abstract_machine
          submodules: recursive
      - name: Install dependencies
        run: |
          cd cognitive_robot_abstract_machine
          source /opt/ros/cram-env/bin/activate
          poetry install
          cd suturo_resources
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: |
          source /opt/ros/overlay_ws/install/setup.bash
          source /opt/ros/cram-env/bin/activate
          python -m pytest -sv suturo_resources/test